### ISSUE TITLE
Missing SpiderMonkey AST node type: Property

### ISSUE THREAD

**Issue by manekinekko** [sourcegraph/acorn-walkall#1]
Hi,

I found an issue when using your module. Here is the log:

```
/Users/xxxxx/node_modules/acorn/util/walk.js:30
      base[type](node, st, c);
                ^
TypeError: Object #<Object> has no method 'Property'
    at c (/Users/xxxxx/node_modules/acorn/util/walk.js:30:17)
    at Object.exports.traverser (/Users/xxxxx/node_modules/walkall/walkall.js:72:24)
    at c (/Users/xxxxx/node_modules/acorn/util/walk.js:30:17)
    at Object.exports.traverser (/Users/xxxxx/node_modules/walkall/walkall.js:76:7)
    at c (/Users/xxxxx/node_modules/acorn/util/walk.js:30:17)
    at Object.exports.traverser (/Users/xxxxx/node_modules/walkall/walkall.js:72:24)
    at c (/Users/xxxxx/node_modules/acorn/util/walk.js:30:17)
    at Object.exports.traverser (/Users/xxxxx/node_modules/walkall/walkall.js:72:24)
    at c (/Users/xxxxx/node_modules/acorn/util/walk.js:30:17)
    at Object.exports.simple (/Users/xxxxx/node_modules/acorn/util/walk.js:33:5)
```

I fixed this issue by adding "Property" to the `exports.types` array.

**Comment by sqs** [comment]
Thanks! Would you be able to submit a PR with the change?

**Comment by manekinekko** [comment]
Hi, here is the PR [https://github.com/sourcegraph/acorn-walkall/pull/2]
